name: CDB PR Workflow

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
      - name: coverage
        run: |
          coverage run -m unittest discover . -p '*.py' -b -vvv
          coverage report -m
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
