name: CDB PR Workflow

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: lint
        run: |
          make lint
      - name: coverage
        run: |
          make coverage
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2