name: CDB PR Workflow

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: lint with flake8
        run: |
          flake8 .
      - name: format with black
        uses: psf/black@stable